apiVersion: v1
kind: Pod
metadata:
  name: palindrome-client
spec:
  containers:
  - name: palindrome-client-container
    image: burgerdev/palindrome-client:latest
    args: ["-c", "palindrome-generator-service:6666"]
