kind: Service
apiVersion: v1
metadata:
  name: palindrome-generator-service
spec:
  selector:
    app: palindrome-label
  ports:
    - name: palindrome-port
      protocol: TCP
      port: 6666
      targetPort: 6666
