apiVersion: v1
kind: Pod
metadata:
  name: palindrome-generator
  labels:
    app: palindrome-label
spec:
  containers:
  - name: palindrome-generator-container
    image: burgerdev/palindrome:latest
